version: '3.7'

services:
  mongodb:
    image: mongo:4.4.3
    container_name: mongodb
    environment:
        MONGO_INITDB_ROOT_USERNAME: dbadmin
        MONGO_INITDB_ROOT_PASSWORD: dbadmin
        MONGO_INITDB_DATABASE: test
    ports:
        - 27017:27017
    volumes:
        - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
        

  rabbitmq:
      image: rabbitmq:3.8-alpine
      container_name: rabbitmq
      volumes:
          - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
          - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
      ports:
          - 5672:5672
          - 15672:15672
